services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    env_file:
        - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CLIENT_PORT: ${CLIENT_PORT}
      SERVER_PORT: ${SERVER_PORT}
    container_name: 'chat-server'
    volumes:
      - ./server:/app
      - /app/node_modules/
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    env_file:
      - ./.env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      VITE_CLIENT_PORT: ${CLIENT_PORT}
      VITE_SERVER_PORT: ${SERVER_PORT}
    container_name: 'chat-client'
    volumes:
      - ./client:/app
      - /app/node_modules/
